name: CI&CD

on:
  push:
    branches:
      - deploy

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Dependent environment
      run: |
        npm i
        node process.js
    - name: Deploy
      uses: garygrossgarten/github-action-scp@v0.5.3
      with:
        local: ./
        remote: /home/ubuntu/www/diandeng.tech/docs
        host: ${{ secrets.HOST }}
        username: ubuntu
        privateKey: ${{ secrets.PRIVATEKEY }}