name: Node CI

on:
  push:
    branches:
    - doc

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: process docs
      run: npm install && node process.js
#       env:
#         CI: true

#     - name: push2
#       run: git push